#!/bin/zsh
set -eu

F=$1
V=$(fgrep -m1 '(dsc) [' $F | cut -d ' ' -f 5)
P=${F#failure-}
P=${P%*.rbuild}

T=$(mktemp)
trap "rm $T" EXIT

cat >$T <<END
From: "Chris West (Faux)" <solo-debianbugs@goeswhere.com>
To: Debian Bug Tracking System <submit@bugs.debian.org>
Subject: $P: FTBFS: 
X-Debbugs-Cc: solo-debianbugs@goeswhere.com

Source: $P
Version: $V
Severity: serious
Justification: fails to build from source
Tags: sid stretch
User: reproducible-builds@lists.alioth.debian.org
Usertags: ftbfs
X-Debbugs-CC: reproducible-builds@lists.alioth.debian.org

Dear Maintainer,

The package fails to build:

$(cat $F)

Full build log:
https://reproducible.debian.net/rb-pkg/unstable/amd64/$P.html

-- System Information:
Debian Release: stretch/sid
APT prefers unstable
APT policy: (500, 'unstable')
Architecture: amd64 (x86_64)
END

mutt -H $T submit@bugs.debian.org

