#!/usr/bin/env node

const parse = require('bash-parser');

// this is a joke, right?
let inputChunks = [];
process.stdin.resume();
process.stdin.on('data', function(chunk) {
    inputChunks.push(chunk);
});

process.stdin.on('end', function () {
    const input = inputChunks.join('');
    process.stdout.write(JSON.stringify(parse(input)));
});
